version: '3.7'

services:
  webapp:
    build:
      context: ../GeoBuyerParser2
      dockerfile: Dockerfile
    container_name: geo-buyer-parser2
    ports:
      - "8081:8081"
    volumes:
      - ./_db_file:/app/db_file/
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: nat
